FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app
COPY TelegramNutritionMockBot.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENV ASPNETCORE_URLS=http://+:5090
EXPOSE 5090
ENTRYPOINT ["dotnet", "TelegramNutritionMockBot.dll"] 